- .gitignore
- pom.xml
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAccount.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployProperties.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryClientFactory.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryInstance.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/DefaultCloudFoundryClientFactory.java
- src/test/groovy/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerSpec.groovy
- src/test/groovy/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryInstanceSpec.groovy
* Handles all the parameters including memory, disk, build pack, and instances
* Chock full of test cases to verify interaction with mocked out CF
* Implements the SPI
* Uses Java 8
> Create Spring Cloud Deployer module for Cloud Foundry

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
- src/test/groovy/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerSpec.groovy
Deploying an already deployed app is supposed to fail. Undeploying a non-existent app is also supposed to fail. This commit updates that to work properly for CF deployments.
> Observe contract on deploying/undeploying

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
Enhance unit testing to not rely solely on TCK for verification.
> Increase unit testing for app deployer

- pom.xml
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncher.java
resolves #45 
depends on https://github.com/spring-cloud/spring-cloud-deployer/pull/78
> environmentProperties now deploymentProperties

- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerIntegrationTests.java
Fixes spring-cloud/spring-cloud-deployer-cloudfoundry#76
> Use MavenProperties in TCK tests

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppInstanceStatus.java
Fixes spring-cloud/spring-cloud-deployer-cloudfoundry#53
> Implemented instance attributes retrieval

- pom.xml
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerIntegrationTests.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncherIntegrationTests.java
Depends on spring-cloud/spring-cloud-deployer#106
Fixes spring-cloud/spring-cloud-deployer-cloudfoundry#80
> Adapt CF ITs to new TCK

- pom.xml
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2620AndEarlierTaskLauncher.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2620AndEarlierTaskLauncherTests.java
Fixes https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/115
> Upgrade reactor-netty and cf-java-client

- pom.xml
This change updates the Cloud Foundry Java Client to the latest released version.
> Cloud Foundry Java Client 2.2.0.RELEASE

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
* Parameterize retry delays
* Clarify getStatus flow using otherwise,
* Tidy up logging
Fixes #136
> Introduce short timeout value on get to eagerly trigger retry

- .gitignore
- pom.xml
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeployerAutoConfiguration.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
Fixes https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/160
> Implement DeployerEnvironmentInfo

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryTaskLauncher.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2620AndEarlierTaskLauncher.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncher.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeployerAutoConfiguration.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2620AndEarlierTaskLauncherTests.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncherTests.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
Fixes https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/162
> Add RuntimeInfo to TaskLauncher

- pom.xml
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncher.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
Fixes https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/164
> Add Docker support for tasks

- pom.xml
> Update spring-cloud-deployer-spi to 1.2.0.RC1

- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
> Update unit tests for update in cf-java-client lib and metrics env-vars

- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
> Remove redundant verify calls

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java
Fixes https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/188
> Increase default status timeout to 5s

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppInstanceStatus.java
> Add URL(s) to status call

- .travis.yml
> Add travis + codecov

- pom.xml
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryTaskLauncher.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncher.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncherTests.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
- Fixes #215 
- Fixed builder validations
- Updated tests to include required properties in some of the builder
objects
- Updated docker method
> Upgraded CFJC

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java
> Add heath endpoint option, make http explicit app health check type

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java
Resolves #201 
Deployer integration tests passed against PWS.
Tests run: 52, Failures: 0, Errors: 0, Skipped: 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:06 min
> Upgrade JBP to v4.7.1

- pom.xml
I ran the IT tests on PWS and it is green.
Resolves spring-cloud/spring-cloud-deployer-cloudfoundry#237
> Upgrade CFJC to 2.25.0

- pom.xml
> Update CFJC to 3.9.0

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncher.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncherTests.java
resolves #247
This allows a task to be staged but not launched.
> CFD now exposes stage command

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncher.java
> Updated staged log message state that the app was staged vs launched.

- pom.xml
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTestSupport.java
> Make version 2.0.0.BUILD-SNAPSHOT

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeployerAutoConfiguration.java
- Add `doOnError` inside version bean intialization
Resolves #263
> Throw exception when connection error occurs

- pom.xml
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
Addresses https://github.com/spring-cloud/spring-cloud-dataflow/issues/2909 providing supplemental log messages for Docker resources and Url resources.
> Add download log messages for URL and Docker resources

- src/main/java/org/springframework/cloud/deployer/scheduler/spi/cloudfoundry/CloudFoundryAppScheduler.java
> Polished the logging added during migration

- src/main/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/CloudFoundryAppScheduler.java
- src/main/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/CloudFoundryScheduleSSLException.java
- src/main/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/CloudFoundrySchedulerProperties.java
- src/main/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/expression/QuartzCronExpression.java
- src/test/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/CloudFoundryAppSchedulerTests.java
- src/test/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/CloudFoundryScheduleSSLExceptionTests.java
- src/test/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/CloudFoundrySchedulerPropertiesTest.java
- src/test/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/SpringCloudSchedulerIntegrationTests.java
- src/test/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/expression/QuartzCronExpressionTests.java
> Refactor scheduler packages into org.springframework.cloud.deployer.spi

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
> Delete local maven artifacts if 'autoDeleteMavenArtifacts' is true

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
> Backport delete local maven artifacts

- README.adoc
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
> Add ability to set additional environment variables in the manifest

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
> Map env from request properties

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvConfigurer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java
- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncher.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncherTests.java
> Make environment in deploymentProperties immutable

- src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppInstanceStatus.java
- src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
> Correct guid attribute value and add index

- README.adoc
> Remove the build status since CI server isn't publically available.

- .github/settings.xml
- pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5193
> Add MavenCentral in place of repo.spring.io/release (#101)

- .github/settings.xml
- pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5193
> Set snapshot=false on Maven Central repos
