spring-cloud/spring-cloud-deployer-cloudfoundry

src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryTaskLauncher.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2620AndEarlierTaskLauncher.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncher.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeployerAutoConfiguration.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2620AndEarlierTaskLauncherTests.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncherTests.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncherIntegrationTests.java

Previously, the `TaskLauncher` was implemented exclusively using Cloud Foundry V3 APIs.  This was done because tasks are part of the V3 API and build on other V3 APIs.  Recently the Cloud Foundry team has requested that we use V2 APIs wherever possible and only use V3 APIs for tasks themselves.  This change updates the code to do that.

Use Cloud Foundry V2 APIs in TaskLauncher

---

pom.xml
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryTaskLauncher.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2620AndEarlierTaskLauncher.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncher.java

Previously, the algorithm for identifying when a task was not found was brittle.  Not only did it examine payload codes and messages, when presented with an unexpected error payload (say across incompatible API changes), it would fail completely.
This change updates the algorithm to take advantage of updates to the Java Client.  Specifically, all CAPI-based APIs now return a subclass of AbstractCloudFoundryException which includes the original HTTP status code, even in the face of an unexpected error payload.  The existence of a 404 NOT FOUND HTTP status code is now the only indication that the task was not found.
In addition to this Java Client API change, the code was also updated to use the much more concise otherwiseReturn() operator in Reactor.  This greatly simplifies the logic and …

Better Identify Not Found Tasks

---

pom.xml

This change updates the version of the Java Client to v2.3.0.RELEASE.  This release addresses issues around token negotiation and reactor-netty connection polling after idle periods.

Java Client Update

---

src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java

* Retry operation heuristics is 0.4*statusTimeout, 500 ms with defaults.
* Check that retry timeout value is never less than 500 ms, log and reset to
500ms if that is the case.
Fixes #143

Set default status timeout value to 2000.  New retry operation heuristic

---

src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncherTests.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java

- updating tests to use buildpack property from CloudFoundryDeploymentProperties
Resolves #173

Switching to use tag v3.14 for java-buildpack

---

src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java

This aligns with the value used in SCDF and is more practical for real world
task situations. Applies not only to running integration tests in the
absence of external (env var) customization, but also when the deployer is
embedded (eg Task Launcher).
Fixes https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/189

Increase default API timeout to 360s.

---

pom.xml

This PR updates CFJC to `2.11.0.BUILD-SNAPSHOT`, which in turn _requires_ reactor-core at `3.0.7.RELEASE` and reactor-netty at `0.6.3.RELEASE`.

Update CFJC and Reactor versions

---

src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java

* Rename property for heath check endpoint from
`health-check-endpoint` to `health-check-http-endpoint` to be consistent
with naming in CF manifest
Fixes #228

Add support for setting health check timeout

---

LICENSE
NOTICE
NOTICE~
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryTaskLauncher.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AppNameGenerator.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncher.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppInstanceStatus.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppNameGenerator.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryConnectionProperties.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeployerAutoConfiguration.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/DurationConverter.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/ServiceParser.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/UnsupportedVersionTaskLauncher.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncherTests.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerIntegrationTests.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppNameGeneratorTest.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncherIntegrationTests.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTestSupport.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/ServiceParserTests.java

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
https://www.apache.org/licenses/ ([https](https://www.apache.org/licenses/) result 200).
https://www.apache.org/licenses/LICENSE-2.0 ([https](https://www.apache.org/licenses/LICENSE-2.0) result 200).

URL Cleanup

---

src/main/resources/META-INF/additional-spring-configuration-metadata.json

- Add value hints for spring.cloud.deployer.cloudfoundry.health-check
using additional-spring-configuration-metadata.json.
- This is a first change of this type which allows UI to catch up
and use real values as type
`org.cloudfoundry.operations.applications.ApplicationHealthCheck`
is naturally unknown outside of java IDE's.
- Fixes #291
NOTE: to see a change in UI needs to be used with https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/1188

Add value hints for health-check property

---

pom.xml
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundry2630AndLaterTaskLauncher.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/UnsupportedVersionTaskLauncher.java

- for both the AppDeployer and TaskLauncher implementations
- Use CF Java Client's interface to retrieve logs
Resolves #295

Implement getLog() for CF

---

src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryTaskLauncher.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncherCachingTests.java

- Modify org/space result caching so that we let empty
and errors getting evicted immediately so that next
request is re-attempted.
- Without this you'd need to restart server to clear out cache.
- New test is throwing conditionally so it should simulate
real scenario.
- Fixes #337

Change not to cache error signals

---

README.adoc
pom.xml
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryTaskLauncher.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvAwareAppDeploymentRequest.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvAwareResource.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvConfigurer.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncher.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvAwareResourceTests.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CfEnvConfigurerTests.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncherTests.java

Resolves #344 
Updated PR since @ilayaperumalg first reviewed it.  
This adds `CfEnfAwareResource` and clones the immutable `AppDeploymentRequest` as `CfEnvAwareApplicationDeploymentRequest` to contain the CfEnvAwareResource.  The app deployer and task launcher do the conversion first in `deploy` and `launch` respectively.  
`CfEnvAwareResource` determines if it includes `CfEnv.class` at creation time and sets its `hasCfEnv` property.  This only applies to boot jars,  e.g. Docker images are not inspected as it would require a docker daemon to inspect the image.  
If CfEnv is present, the deployer will:
* disable auto-reconfiguration in the Java build pack
* activate the cloud profile if it is not already declared active in any external property source (environment variable, application …

Automatically configure environment for CfEnv

---

src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryConnectionProperties.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeployerAutoConfiguration.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryConnectionPropertiesTests.java

- New connection props client-id and client-sercet.
- If defined, pass those into PasswordGrantTokenProvider where client-id would
effectively change its default `cf` value for id.
- Fixes #348

Customise platform client id and secret

---

pom.xml
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployer.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java
src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncher.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeployerTests.java

- Switch to using cf-java-client snapshots as
new feature is there.
- Deprecate old buildpack setting and favour buildpacks
if set and fallback to buildpack until deprecation
is removed in future.
- Fixes #327

Support multiple buildpacks

---

src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/AbstractCloudFoundryDeployer.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java

Fixes #355 
Deploy with `deployer.*.cloudfoundry.env.ROOT.LOG.LEVEL=DEBUG`
```
$cf env time2
....
User-Provided:
ROOT.LOG.LEVEL: DEBUG
SPRING_APPLICATION_JSON: {"spring.datasource.username":"sa","spring.cloud.task.name":"time2","spring.datasource.url":"jdbc:h2:tcp://localhost:19092/mem:dataflow","spring.datasource.driverClassName":"org.h2.Driver"}
```

Map env from request properties

---

src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncher.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryTaskLauncherTests.java

Currently the build pack launcher can't handle unescaped parenthesis which are required when users specify type for job parameters.
resolves #359
Refer to https://github.com/spring-cloud/spring-cloud-dataflow/issues/4216

Add support to task launcher to support `(` and `)` in cmd line args

---

src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeploymentProperties.java
src/main/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/CloudFoundryAppScheduler.java
src/main/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/CloudFoundrySchedulerProperties.java
src/test/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/CloudFoundryAppSchedulerTests.java
src/test/java/org/springframework/cloud/deployer/spi/scheduler/cloudfoundry/SpringCloudSchedulerIntegrationIT.java

Scheduler properties should be retrieved from the deployment properties:
Child of https://github.com/spring-cloud/spring-cloud-dataflow/issues/4262
resolves #377

Deprecates Scheduler Property

---

src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppInstanceStatus.java
src/test/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryAppDeployerTests.java

The guid-only value will be exposed as "cf-guid" in this [upcoming PR](https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/385/files#diff-5357d11483b96e0b8419d35037f94ec0370327aebe194f2bca0b808e7cce43d8R120) for actuator access.
Fixes https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/issues/353
cc: @dturanski

Restore unique 'guid' values for each app instance (include index)

---

src/main/resources/META-INF/spring.factories
src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

It is discussed here: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration And is required if 3.x boot apps need to use this project.

Migrate spring.factories to autoconfiguration.imports per boot standard
